python3 train.py \
    --use_amp \
    --epochs 100 \
    --batch_size 16 \
    --project VITON-HD \
    --shuffle \
    --load_height 1024 \
    --load_width 768 \
    --use_wandb \
    --log_interval 20 \
    --workers 4 \
    --dataset_dir /home/azureuser/data/docker_data
