python3 train.py \
    --use_amp \
    --epochs 100 \
    --batch_size 16 \
    --project VITON-HD \
    --shuffle \
    --sync_bn \
    --load_height 1024 \
    --load_width 768 \
    --use_wandb \
    --log_interval 100 \
    --workers 4
